#index:
#    path: /
#    controller: App\Controller\DefaultController::index


hello:
   path: /hi
   controller: App\Controller\HelloController::hello

create_recipe:
   path: /recipe
   controller: App\Controller\RecipeController::createRecipe


