#index:
#    path: /
#    controller: App\Controller\DefaultController::index


hello:
   path: /hi
   controller: App\Controller\HelloController::hello

create_recipe:
   path: /recipe/create
   controller: App\Controller\RecipeController::createRecipe

show_recipe:
   path: /recipe/{id}
   controller: App\Controller\RecipeController::show

list_recipe:
   path: /recipe
   controller: App\Controller\RecipeController::listRecipe

update_recipe:
   path: /recipe/update/{id}
   controller: App\Controller\RecipeController::update

delete_recipe:
   path: /recipe/del/{id}
   controller: App\Controller\RecipeController::delete


